---
- name: playbook that changes password of a user
  hosts: all ### REMEMBER TO USE LIMIT
  become: true
  vars_prompt:
    - name: user_name
      prompt: "Enter User Name: "
      private: false
    - name: user_password
      prompt: "Enter the desired password: "
      private: true

  tasks:
    - name: Change users password
      ansible.builtin.user:
        name: "{{ user_name  }}"
        password: "{{ user_password | password_hash('sha512') }}"
        state: present
