---
- hosts: all
  become: yes
  become_user: root
  remote_user: ramiraz
  vars_prompt:
    - name: user_name
      prompt: "Enter the user name:"
      private: no
    - name: user_password
      prompt: "Enter the user password:"
      private: yes

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ user_name }}"
        state: present
        password: "{{ user_password | password_hash('sha512') }}"
        groups: wheel
        create_home: true

    - name: Create drop-in sudoers file
      file:
        path: /etc/sudoers.d/{{ user_name }}
        state: touch
        owner: root
        group: root
        mode: 0440

    - name: add line in sudoers file
      lineinfile:
        dest: /etc/sudoers.d/{{ user_name }}
        state: present
        line: '{{ user_name }} ALL=(ALL) NOPASSWD:ALL'

    - name: create .ssh if it does not exist
      file:
        path: /home/{{ user_name }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ user_name }}"
        group: "{{ user_name }}"

    - name: copy authorized_keys file
      copy:
        src: authorized_keys
        dest: /home/{{ user_name }}/.ssh/authorized_keys
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0600'
        backup: yes
